#
<<<<<<< HEAD:scweb/azure-pipelines.yaml
# Azure pipeline to build and publishe a hugo blog release
=======
# Azure pipeline to build and publish a hugo blog release
>>>>>>> 7a9d1b6aa396f4b2bd08430c617311cdda0df993:azure-pipelines.yaml
# github.com/kurtmkurtm
#

trigger:
<<<<<<< HEAD:scweb/azure-pipelines.yaml
  - master
  
  pool:
    vmImage: 'ubuntu-16.04'
  
  variables:
    hugo.version: '0.58.2'
    blog.path: '.'
  
  steps:
  - script: |
     wget -c https://github.com/gohugoio/hugo/releases/download/v$(hugo.version)/hugo_$(hugo.version)_Linux-64bit.deb   
    displayName: 'Download HUGO'
  
  - script: 'sudo dpkg -i hugo_$(hugo.version)_Linux-64bit.deb'
    displayName: 'Install HUGO'
  
  - script: |
     cd $(blog.path)
     hugo  --log -v
    displayName: 'Generate Blog'
  
  - task: CopyFiles@2
    displayName: 'Copy Blog'
    inputs:
      SourceFolder: '$(blog.path)/public'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Blog'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
=======
- master

pool:
  vmImage: "ubuntu-16.04"

variables:
  hugo.version: '0.58.2'
  blog.path: './scweb'

steps:
- script: |
   wget -c https://github.com/gohugoio/hugo/releases/download/v$(hugo.version)/hugo_$(hugo.version)_Linux-64bit.deb   
  displayName: "Download HUGO"

- script: 'sudo dpkg -i hugo_$(hugo.version)_Linux-64bit.deb'
  displayName: "Install HUGO"

- script: |
   cd $(blog.path)
   hugo --log -v
  displayName: 'Generate Blog'

- task: CopyFiles@2
  displayName: 'Copy Blog'
  inputs:
    SourceFolder: '$(blog.path)/public'
    Contents: "**"
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish Blog
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: Drop
    publishLocation: 'Container'
>>>>>>> 7a9d1b6aa396f4b2bd08430c617311cdda0df993:azure-pipelines.yaml
